### ISSUE TITLE
daemon won't start at boot

### ISSUE THREAD

**Issue by everlanes** [jordi-pujol/wwanHotspot#21]
I have a backup device running OpenWRT. So I am not using it as router or hotspot.
All I want is the wifi to try to connect to one of the defined wifi networks until it succeeds. If the connection is lost, it should just start to try to reconnect. Something like a normal laptop would do.

This works once I start the service manually. But, I just can't figure out, how to start the daemon after boot.

Looking at the source code the daemon is intentionally not startet at boot time but should be started by a hotplug event. As I am not using the lan port this hotplug event for connection lan is never fired. So the service never comes up.

Is there any other way I could start wwanHotspot? Do I miss anything? Or would my case better solved with another tool?

**Comment by jordi-pujol** [comment]
So, you have a little problem starting the daemon and all the rest works. 
Really do you think that there is another tool that solves this little problem and has the same functionality ? Have you already found this wonderful tool ?
Let's try to solve this problem and don't make fantasy.

First, check that the setup of this daemon is correct. The daemon should be enabled, and already you talk that this daemon works when started.

Second, the daemon is started when any network change occurs but not at boot time. 
This procedure is working for me, however at boot time may be in some routers the network has been setup before that wwanHotspot starts.
a- You may try to remove the check at boot time. May be this will solve the problem.
b- or you may try that a network change reloads the daemon instead of sending a network signal. I don't recommend it.
c- The hardest solution to hack this problem is setup a cron command that restarts the daemon when it's not running.

/etc/init.d/wwanHotspot running || /etc/init.d/wwanHotspot restart

**Comment by everlanes** [comment]
> So, you have a little problem starting the daemon and all the rest works.
> Really do you think that there is another tool that solves this little problem and has the same functionality ?
> Have you already found this wonderful tool ?

I don't know, why you have to be that snippy? I was just wondering, whether I try to use the wrong tool/solution/path for my problem. Because I see, that this tool is not originally intended for my setup. I am not trying to setup a hotspot/repeater, but only a wifi client.

> First, check that the setup of this daemon is correct. The daemon should be enabled, and already you talk that this daemon works when started.

Yes, the daemon is setup correct. 

> Second, the daemon is started when any network change occurs but not at boot time.

That seems to be a problem for my setup. I don't plug in any ethernet cable, as I don't use it as repeater. Besides it is not triggert for any network change. In the script `/etc/hotplug.d/iface/99-wwanHotspot` it is tested for interface `lan`. So only changes to this interface would trigger a start of the daemon. Is my understanding correct?

I added a debug script
```
cat /etc/hotplug.d/iface/00-logger 
logger -t hotplug $(env)
```

Looking at the debug log with `logread` it seems, that the `ifup` event takes about 10 minutes to occur after a network cable is attached.

> a- You may try to remove the check at boot time. May be this will solve the problem.

Yes, i tried this. But removing the check does not seem to be enough. I also have to remove the check for interface `lan` in the hotplug script. Honestly, I don't understand, what is happening there.

> b- or you may try that a network change reloads the daemon instead of sending a network signal. I don't recommend it.

Could you please give me more information on that? I don't understand, what you mean.

> c- The hardest solution to hack this problem is setup a cron command that restarts the daemon when it's not running.
> /etc/init.d/wwanHotspot running || /etc/init.d/wwanHotspot restart

For me this seems to be the most reliable solution. Why do you think, that it is hard?

**Comment by everlanes** [comment]
Just for reference and completeness: I am using a custom image built from current snapshot:
```
cat /etc/os-release 
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="https://openwrt.org/"
BUG_URL="https://bugs.openwrt.org/"
SUPPORT_URL="https://forum.openwrt.org/"
BUILD_ID="r18710-dc2da6a233"
OPENWRT_BOARD="ramips/mt7620"
OPENWRT_ARCH="mipsel_24kc"
OPENWRT_TAINTS=""
OPENWRT_DEVICE_MANUFACTURER="OpenWrt"
OPENWRT_DEVICE_MANUFACTURER_URL="https://openwrt.org/"
OPENWRT_DEVICE_PRODUCT="Generic"
OPENWRT_DEVICE_REVISION="v0"
OPENWRT_RELEASE="OpenWrt SNAPSHOT r18710-dc2da6a233"
```

**Comment by everlanes** [comment]
Ok, I tried solution c) and added a cron job that checks every minute if the daemon is running. Now after a reboot the wifi comes up (after around 3 minutes) and is connected successfully. I think this is the most reliable solution for my setup.

I am closing this request now. Thanks

**Comment by jordi-pujol** [comment]
I was not snippy, has been the right answer to your request, 
You have not introduced yourself, 
You did not consider that this tool is free and has been developed with unpaid resources. 
Also you said that this tool doesn't fit your requirements because you have found a little problem, therefore you suppose that there are other tools that work better, Does it mean that this tool is bad ?
I have no obligation to answer you and I could send you on your way right now .
Be more friendly and less demanding.

At this point the answer is simple, stop talking and let's think, start working in every aspect that I have pointed,

**Comment by jordi-pujol** [comment]
For reference, I'm writing this for any person that reads it with a minimum of sense,

The hack of adding a cron job is not a solution, as I've said, it's only a hack.
The right solution is analyze the system boot process and make the right changes in the init script to do the daemon run on any circumstances.
