### ISSUE TITLE
Can't connect to Hotspot, probably configuration is not correct

### ISSUE THREAD

**Issue by mcdull** [jordi-pujol/wwanHotspot#5]
I have a Hotspot with NO password but with Captive portal (i.e. open hotspot).
In using wwanHotspot, it will not automatically connect to this hotspot.  I enabled debug and following info in the log file

assume ssid for the hotspot is AA-BB.CC DD EE  (it is in the same pattern of the real hotspot name)

`
+ ssid=1:AA-BB.CC DD EE
+ uci =q get wireless.@wifi-iface[1].disabled
+ wifi_disable=0
+ [ AA-BB.CC DD EE != AA-BB.CC DD EE ]  <-- this one I have checked carefully that they are the same string
+ [ 0 = 1]
+ [ 1179 -gt 3 ]
+ ScanRequest = 0
+ +log Error: can't connect to the Hotspots, probably configuration is not correct.
`

My wwanHotspot config file has 3 defined hotspot from net1 to net3.  For others, they are with empty string.

Below is the entry,

net1_ssid="AA-BB.CC DD EE"
net1_encrypt="none"  <-- should it be none or empty?
net1_key=""

**Comment by jordi-pujol** [comment]
please set manually in your router the parameters of this access point,
check that the clients connect successfully
and therefore query the current values and note it,
To query use the following commands:
   ```
   uci -q get wireless.@wifi-iface[1].ssid
   uci -q get wireless.@wifi-iface[1].encryption
   uci -q get wireless.@wifi-iface[1].key
   ```
This time I hope you will let me know something about this,

**Comment by mcdull** [comment]
uci -q get wireless.@wifi-iface[1].ssid
AA-BB.CC DD EE
uci -q get wireless.@wifi-iface[1].encryption
none
uci -q get wireless.@wifi-iface[1].key
<<nothing>>

On more thing is that whenever the daemon is working and no hotspot is connected, the wifi will keep disconnecting.  But I suspect that it is hardware related. As I am using the same radio0 for AP and STA.

**Comment by jordi-pujol** [comment]
you said:
"scan multiple AP station with the same ssid (all belongs to the same network)"

I can't believe that this could work anyway.

**Comment by mcdull** [comment]
This is the most common setting for Hotspots.
Different AP with same ssid to cover different parts of the building.  
The client would connected to the AP with strongest signal unless supplied with bssid.

**Comment by jordi-pujol** [comment]
you should read the basic theory about WLAN and try to undestand it,
This issue is closed, please don't bother me on your faulty configurations.

**Comment by mcdull** [comment]
Thank you for you help anyway.  Sorry for your time.  I will revert to my original setting which works fine.
Just without the capability to auto switch hotspot function.

**Comment by jordi-pujol** [comment]
Simply look at the definition of ID; an identification's name must be unique to identify something, All these configurations are wrong.
A configuration like this, with duplicated ID's works and fails erratically, it happens that a wireless client station will be allways connecting and disconnecting, and wwanHotspot will detect it.
May be for the network administrator this configuration is easy and also has some doubtful use when the clients doesn't require a much reliable wireless network, but I have not plans for wwanHotspot to support this kind of nightmare because it's impossible. Connecting from a wireless Access Point to another implies a disconnection, is detected by OpenWrt that sends an interrupt to wwanHotspot, so it counts as another network error.
Also I think that a responsible administrator should never configure this way a wireless network.

**Comment by jordi-pujol** [comment]
If anyone wants to expose some other info please post on a new issue.

**Comment by mcdull** [comment]
@nh905  jordi-pujol was right, the configuration was wrong. It is up to his decision to design the configuration so it is always true for his program to handle in whatever way.  I am a noob in wireless network, and maybe that's the reason why using SSID as a unique key make no sense to me.  In my home, I can see like 10s of ssid named "dlink" or "netgear".  To me, I only think of bssid as the unique key.  Anyway, I have given up on this one until I read the basic theory about WLAN again.
